---
- name: Install git (debian/ubuntu)
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Install dependencies (debian/ubuntu)
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3
    - python3-apt

- name: Install mailx (debian/ubuntu)
  apt:
    name: "{{check_updates_mailer_quiet_pkg}}"
    state: latest
  when: check_updates_quiet
