---
- name: Install git (debian/ubuntu)
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Install dependencies (debian/ubuntu)
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3
    - python3-apt
